package rtg.config.vanilla;

import java.io.File;

import org.apache.logging.log4j.Level;

import rtg.world.biome.BiomeBase;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

import net.minecraftforge.common.config.Configuration;

public class ConfigVanilla
{
	public static Configuration config;
	
	public static final int biomeWeightMin = BiomeBase.MIN_BIOME_WEIGHT;
	public static final int biomeWeightMax = BiomeBase.MAX_BIOME_WEIGHT;
	public static final int biomeWeightDefault = BiomeBase.DEFAULT_BIOME_WEIGHT;
	
	public static boolean generateVanillaBiomes = true;
	
    public static boolean generateVanillaBeach = true;
    public static boolean generateVanillaBirchForest = true;
    public static boolean generateVanillaBirchForestHills = true;
    public static boolean generateVanillaBirchForestHillsM = true;
    public static boolean generateVanillaBirchForestM = true;
    public static boolean generateVanillaColdBeach = true;
    public static boolean generateVanillaColdTaiga = true;
    public static boolean generateVanillaColdTaigaHills = true;
    public static boolean generateVanillaColdTaigaM = true;
    public static boolean generateVanillaDeepOcean = true;
    public static boolean generateVanillaDesert = true;
    public static boolean generateVanillaDesertHills = true;
    public static boolean generateVanillaDesertM = true;
    public static boolean generateVanillaExtremeHills = true;
    public static boolean generateVanillaExtremeHillsM = true;
    public static boolean generateVanillaExtremeHillsPlus = true;
    public static boolean generateVanillaExtremeHillsPlusM = true;
    public static boolean generateVanillaFlowerForest = true;
    public static boolean generateVanillaForest = true;
    public static boolean generateVanillaForestHills = true;
    public static boolean generateVanillaFrozenRiver = true;
    public static boolean generateVanillaIceMountains = true;
    public static boolean generateVanillaIcePlains = true;
    public static boolean generateVanillaIcePlainsSpikes = true;
    public static boolean generateVanillaJungle = true;
    public static boolean generateVanillaJungleEdge = true;
    public static boolean generateVanillaJungleEdgeM = true;
    public static boolean generateVanillaJungleHills = true;
    public static boolean generateVanillaJungleM = true;
    public static boolean generateVanillaMegaSpruceTaiga = true;
    public static boolean generateVanillaMegaTaiga = true;
    public static boolean generateVanillaMegaTaigaHills = true;
    public static boolean generateVanillaMesa = true;
    public static boolean generateVanillaMesaBryce = true;
    public static boolean generateVanillaMesaPlateau = true;
    public static boolean generateVanillaMesaPlateau_F = true;
    public static boolean generateVanillaMesaPlateauFM = true;
    public static boolean generateVanillaMesaPlateauM = true;
    public static boolean generateVanillaMushroomIsland = false;
    public static boolean generateVanillaMushroomIslandShore = false;
    public static boolean generateVanillaOcean = true;
    public static boolean generateVanillaPlains = true;
    public static boolean generateVanillaRiver = true;
    public static boolean generateVanillaRoofedForest = true;
    public static boolean generateVanillaRoofedForestM = true;
    public static boolean generateVanillaSavanna = true;
    public static boolean generateVanillaSavannaM = true;
    public static boolean generateVanillaSavannaPlateau = true;
    public static boolean generateVanillaSavannaPlateauM = true;
    public static boolean generateVanillaStoneBeach = true;
    public static boolean generateVanillaSunflowerPlains = true;
    public static boolean generateVanillaSwampland = true;
    public static boolean generateVanillaSwamplandM = true;
    public static boolean generateVanillaTaiga = true;
    public static boolean generateVanillaTaigaHills = true;
    public static boolean generateVanillaTaigaM = true;
	
    public static int weightVanillaBeach = (int)Math.floor((double)(biomeWeightDefault * 0.2));
    public static int weightVanillaBirchForest = biomeWeightDefault;
    public static int weightVanillaBirchForestHills = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaBirchForestHillsM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaBirchForestM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaColdBeach = (int)Math.floor((double)(biomeWeightDefault * 0.2));
    public static int weightVanillaColdTaiga = biomeWeightDefault;
    public static int weightVanillaColdTaigaHills = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaColdTaigaM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaDeepOcean = (int)Math.floor((double)(biomeWeightDefault * 1.2));
    public static int weightVanillaDesert = biomeWeightDefault;
    public static int weightVanillaDesertHills = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaDesertM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaExtremeHills = biomeWeightDefault;
    public static int weightVanillaExtremeHillsM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaExtremeHillsPlus = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaExtremeHillsPlusM = (int)Math.floor((double)(biomeWeightDefault * 0.2));
    public static int weightVanillaFlowerForest = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaForest = biomeWeightDefault;
    public static int weightVanillaForestHills = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaFrozenRiver = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaIceMountains = (int)Math.floor((double)(biomeWeightDefault * 0.2));
    public static int weightVanillaIcePlains = biomeWeightDefault;
    public static int weightVanillaIcePlainsSpikes = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaJungle = biomeWeightDefault;
    public static int weightVanillaJungleEdge = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaJungleEdgeM = (int)Math.floor((double)(biomeWeightDefault * 0.2));
    public static int weightVanillaJungleHills = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaJungleM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaMegaSpruceTaiga = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaMegaTaiga = biomeWeightDefault;
    public static int weightVanillaMegaTaigaHills = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaMesa = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaMesaBryce = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaMesaPlateau = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaMesaPlateau_F = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaMesaPlateauFM = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaMesaPlateauM = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaMushroomIsland = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaMushroomIslandShore = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaOcean = (int)Math.floor((double)(biomeWeightDefault * 1.2));
    public static int weightVanillaPlains = biomeWeightDefault;
    public static int weightVanillaRiver = (int)Math.floor((double)(biomeWeightDefault * 0.1));
    public static int weightVanillaRoofedForest = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaRoofedForestM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaSavanna = biomeWeightDefault;
    public static int weightVanillaSavannaM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaSavannaPlateau = (int)Math.floor((double)(biomeWeightDefault * 0.6));
    public static int weightVanillaSavannaPlateauM = (int)Math.floor((double)(biomeWeightDefault * 0.2));
    public static int weightVanillaStoneBeach = (int)Math.floor((double)(biomeWeightDefault * 0.2));
    public static int weightVanillaSunflowerPlains = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaSwampland = biomeWeightDefault;
    public static int weightVanillaSwamplandM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    public static int weightVanillaTaiga = biomeWeightDefault;
    public static int weightVanillaTaigaHills = (int)Math.floor((double)(biomeWeightDefault * 0.8));
    public static int weightVanillaTaigaM = (int)Math.floor((double)(biomeWeightDefault * 0.4));
    
    public static boolean villageVanillaBeach = true;
    public static boolean villageVanillaBirchForest = true;
    public static boolean villageVanillaBirchForestHills = true;
    public static boolean villageVanillaBirchForestHillsM = true;
    public static boolean villageVanillaBirchForestM = true;
    public static boolean villageVanillaColdBeach = true;
    public static boolean villageVanillaColdTaiga = true;
    public static boolean villageVanillaColdTaigaHills = true;
    public static boolean villageVanillaColdTaigaM = true;
    public static boolean villageVanillaDeepOcean = false;
    public static boolean villageVanillaDesert = true;
    public static boolean villageVanillaDesertHills = true;
    public static boolean villageVanillaDesertM = true;
    public static boolean villageVanillaExtremeHills = true;
    public static boolean villageVanillaExtremeHillsM = true;
    public static boolean villageVanillaExtremeHillsPlus = true;
    public static boolean villageVanillaExtremeHillsPlusM = true;
    public static boolean villageVanillaFlowerForest = true;
    public static boolean villageVanillaForest = true;
    public static boolean villageVanillaForestHills = true;
    //public static boolean villageVanillaFrozenRiver = true;
    public static boolean villageVanillaIceMountains = true;
    public static boolean villageVanillaIcePlains = true;
    public static boolean villageVanillaIcePlainsSpikes = true;
    public static boolean villageVanillaJungle = true;
    public static boolean villageVanillaJungleEdge = true;
    public static boolean villageVanillaJungleEdgeM = true;
    public static boolean villageVanillaJungleHills = true;
    public static boolean villageVanillaJungleM = true;
    public static boolean villageVanillaMegaSpruceTaiga = true;
    public static boolean villageVanillaMegaTaiga = true;
    public static boolean villageVanillaMegaTaigaHills = true;
    public static boolean villageVanillaMesa = true;
    public static boolean villageVanillaMesaBryce = true;
    public static boolean villageVanillaMesaPlateau = true;
    public static boolean villageVanillaMesaPlateau_F = true;
    public static boolean villageVanillaMesaPlateauFM = true;
    public static boolean villageVanillaMesaPlateauM = true;
    public static boolean villageVanillaMushroomIsland = true;
    public static boolean villageVanillaMushroomIslandShore = true;
    public static boolean villageVanillaOcean = false;
    public static boolean villageVanillaPlains = true;
    //public static boolean villageVanillaRiver = true;
    public static boolean villageVanillaRoofedForest = true;
    public static boolean villageVanillaRoofedForestM = true;
    public static boolean villageVanillaSavanna = true;
    public static boolean villageVanillaSavannaM = true;
    public static boolean villageVanillaSavannaPlateau = true;
    public static boolean villageVanillaSavannaPlateauM = true;
    public static boolean villageVanillaStoneBeach = true;
    public static boolean villageVanillaSunflowerPlains = true;
    public static boolean villageVanillaSwampland = true;
    public static boolean villageVanillaSwamplandM = true;
    public static boolean villageVanillaTaiga = true;
    public static boolean villageVanillaTaigaHills = true;
    public static boolean villageVanillaTaigaM = true;
	
	public static void init(File configFile) 
	{
		config = new Configuration(configFile);
		
		try 
		{
			config.load();

			generateVanillaBiomes = config.getBoolean("Allow vanilla biomes to generate", "Allow vanilla biomes", generateVanillaBiomes, "If TRUE, uses the individual biome settings below. If FALSE, disables all biomes from this mod.");

            generateVanillaBeach = config.getBoolean("generateVanillaBeach", "Biomes", generateVanillaBeach, "");
            generateVanillaBirchForest = config.getBoolean("generateVanillaBirchForest", "Biomes", generateVanillaBirchForest, "");
            generateVanillaBirchForestHills = config.getBoolean("generateVanillaBirchForestHills", "Biomes", generateVanillaBirchForestHills, "");
            generateVanillaBirchForestHillsM = config.getBoolean("generateVanillaBirchForestHillsM", "Biomes", generateVanillaBirchForestHillsM, "");
            generateVanillaBirchForestM = config.getBoolean("generateVanillaBirchForestM", "Biomes", generateVanillaBirchForestM, "");
            generateVanillaColdBeach = config.getBoolean("generateVanillaColdBeach", "Biomes", generateVanillaColdBeach, "");
            generateVanillaColdTaiga = config.getBoolean("generateVanillaColdTaiga", "Biomes", generateVanillaColdTaiga, "");
            generateVanillaColdTaigaHills = config.getBoolean("generateVanillaColdTaigaHills", "Biomes", generateVanillaColdTaigaHills, "");
            generateVanillaColdTaigaM = config.getBoolean("generateVanillaColdTaigaM", "Biomes", generateVanillaColdTaigaM, "");
            generateVanillaDeepOcean = config.getBoolean("generateVanillaDeepOcean", "Biomes", generateVanillaDeepOcean, "");
            generateVanillaDesert = config.getBoolean("generateVanillaDesert", "Biomes", generateVanillaDesert, "");
            generateVanillaDesertHills = config.getBoolean("generateVanillaDesertHills", "Biomes", generateVanillaDesertHills, "");
            generateVanillaDesertM = config.getBoolean("generateVanillaDesertM", "Biomes", generateVanillaDesertM, "");
            generateVanillaExtremeHills = config.getBoolean("generateVanillaExtremeHills", "Biomes", generateVanillaExtremeHills, "");
            generateVanillaExtremeHillsM = config.getBoolean("generateVanillaExtremeHillsM", "Biomes", generateVanillaExtremeHillsM, "");
            generateVanillaExtremeHillsPlus = config.getBoolean("generateVanillaExtremeHillsPlus", "Biomes", generateVanillaExtremeHillsPlus, "");
            generateVanillaExtremeHillsPlusM = config.getBoolean("generateVanillaExtremeHillsPlusM", "Biomes", generateVanillaExtremeHillsPlusM, "");
            generateVanillaFlowerForest = config.getBoolean("generateVanillaFlowerForest", "Biomes", generateVanillaFlowerForest, "");
            generateVanillaForest = config.getBoolean("generateVanillaForest", "Biomes", generateVanillaForest, "");
            generateVanillaForestHills = config.getBoolean("generateVanillaForestHills", "Biomes", generateVanillaForestHills, "");
            generateVanillaFrozenRiver = config.getBoolean("generateVanillaFrozenRiver", "Biomes", generateVanillaFrozenRiver, "This setting is ignored. Frozen Rivers will always generate, even if set to false.");
            generateVanillaIceMountains = config.getBoolean("generateVanillaIceMountains", "Biomes", generateVanillaIceMountains, "");
            generateVanillaIcePlains = config.getBoolean("generateVanillaIcePlains", "Biomes", generateVanillaIcePlains, "");
            generateVanillaIcePlainsSpikes = config.getBoolean("generateVanillaIcePlainsSpikes", "Biomes", generateVanillaIcePlainsSpikes, "");
            generateVanillaJungle = config.getBoolean("generateVanillaJungle", "Biomes", generateVanillaJungle, "");
            generateVanillaJungleEdge = config.getBoolean("generateVanillaJungleEdge", "Biomes", generateVanillaJungleEdge, "");
            generateVanillaJungleEdgeM = config.getBoolean("generateVanillaJungleEdgeM", "Biomes", generateVanillaJungleEdgeM, "");
            generateVanillaJungleHills = config.getBoolean("generateVanillaJungleHills", "Biomes", generateVanillaJungleHills, "");
            generateVanillaJungleM = config.getBoolean("generateVanillaJungleM", "Biomes", generateVanillaJungleM, "");
            generateVanillaMegaSpruceTaiga = config.getBoolean("generateVanillaMegaSpruceTaiga", "Biomes", generateVanillaMegaSpruceTaiga, "");
            generateVanillaMegaTaiga = config.getBoolean("generateVanillaMegaTaiga", "Biomes", generateVanillaMegaTaiga, "");
            generateVanillaMegaTaigaHills = config.getBoolean("generateVanillaMegaTaigaHills", "Biomes", generateVanillaMegaTaigaHills, "");
            generateVanillaMesa = config.getBoolean("generateVanillaMesa", "Biomes", generateVanillaMesa, "");
            generateVanillaMesaBryce = config.getBoolean("generateVanillaMesaBryce", "Biomes", generateVanillaMesaBryce, "");
            generateVanillaMesaPlateau = config.getBoolean("generateVanillaMesaPlateau", "Biomes", generateVanillaMesaPlateau, "");
            generateVanillaMesaPlateau_F = config.getBoolean("generateVanillaMesaPlateau_F", "Biomes", generateVanillaMesaPlateau_F, "");
            generateVanillaMesaPlateauFM = config.getBoolean("generateVanillaMesaPlateauFM", "Biomes", generateVanillaMesaPlateauFM, "");
            generateVanillaMesaPlateauM = config.getBoolean("generateVanillaMesaPlateauM", "Biomes", generateVanillaMesaPlateauM, "");
            generateVanillaMushroomIsland = config.getBoolean("generateVanillaMushroomIsland", "Biomes", generateVanillaMushroomIsland, "");
            generateVanillaMushroomIslandShore = config.getBoolean("generateVanillaMushroomIslandShore", "Biomes", generateVanillaMushroomIslandShore, "");
            generateVanillaOcean = config.getBoolean("generateVanillaOcean", "Biomes", generateVanillaOcean, "");
            generateVanillaPlains = config.getBoolean("generateVanillaPlains", "Biomes", generateVanillaPlains, "");
            generateVanillaRiver = config.getBoolean("generateVanillaRiver", "Biomes", generateVanillaRiver, "This setting is ignored. Rivers will always generate, even if set to false.");
            generateVanillaRoofedForest = config.getBoolean("generateVanillaRoofedForest", "Biomes", generateVanillaRoofedForest, "");
            generateVanillaRoofedForestM = config.getBoolean("generateVanillaRoofedForestM", "Biomes", generateVanillaRoofedForestM, "");
            generateVanillaSavanna = config.getBoolean("generateVanillaSavanna", "Biomes", generateVanillaSavanna, "");
            generateVanillaSavannaM = config.getBoolean("generateVanillaSavannaM", "Biomes", generateVanillaSavannaM, "");
            generateVanillaSavannaPlateau = config.getBoolean("generateVanillaSavannaPlateau", "Biomes", generateVanillaSavannaPlateau, "");
            generateVanillaSavannaPlateauM = config.getBoolean("generateVanillaSavannaPlateauM", "Biomes", generateVanillaSavannaPlateauM, "");
            generateVanillaStoneBeach = config.getBoolean("generateVanillaStoneBeach", "Biomes", generateVanillaStoneBeach, "");
            generateVanillaSunflowerPlains = config.getBoolean("generateVanillaSunflowerPlains", "Biomes", generateVanillaSunflowerPlains, "");
            generateVanillaSwampland = config.getBoolean("generateVanillaSwampland", "Biomes", generateVanillaSwampland, "");
            generateVanillaSwamplandM = config.getBoolean("generateVanillaSwamplandM", "Biomes", generateVanillaSwamplandM, "");
            generateVanillaTaiga = config.getBoolean("generateVanillaTaiga", "Biomes", generateVanillaTaiga, "");
            generateVanillaTaigaHills = config.getBoolean("generateVanillaTaigaHills", "Biomes", generateVanillaTaigaHills, "");
            generateVanillaTaigaM = config.getBoolean("generateVanillaTaigaM", "Biomes", generateVanillaTaigaM, "");
            
            weightVanillaBeach = config.getInt("weightVanillaBeach", "Weights", weightVanillaBeach, biomeWeightMin, biomeWeightMax, "");
            weightVanillaBirchForest = config.getInt("weightVanillaBirchForest", "Weights", weightVanillaBirchForest, biomeWeightMin, biomeWeightMax, "");
            weightVanillaBirchForestHills = config.getInt("weightVanillaBirchForestHills", "Weights", weightVanillaBirchForestHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaBirchForestHillsM = config.getInt("weightVanillaBirchForestHillsM", "Weights", weightVanillaBirchForestHillsM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaBirchForestM = config.getInt("weightVanillaBirchForestM", "Weights", weightVanillaBirchForestM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaColdBeach = config.getInt("weightVanillaColdBeach", "Weights", weightVanillaColdBeach, biomeWeightMin, biomeWeightMax, "");
            weightVanillaColdTaiga = config.getInt("weightVanillaColdTaiga", "Weights", weightVanillaColdTaiga, biomeWeightMin, biomeWeightMax, "");
            weightVanillaColdTaigaHills = config.getInt("weightVanillaColdTaigaHills", "Weights", weightVanillaColdTaigaHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaColdTaigaM = config.getInt("weightVanillaColdTaigaM", "Weights", weightVanillaColdTaigaM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaDeepOcean = config.getInt("weightVanillaDeepOcean", "Weights", weightVanillaDeepOcean, biomeWeightMin, biomeWeightMax, "");
            weightVanillaDesert = config.getInt("weightVanillaDesert", "Weights", weightVanillaDesert, biomeWeightMin, biomeWeightMax, "");
            weightVanillaDesertHills = config.getInt("weightVanillaDesertHills", "Weights", weightVanillaDesertHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaDesertM = config.getInt("weightVanillaDesertM", "Weights", weightVanillaDesertM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaExtremeHills = config.getInt("weightVanillaExtremeHills", "Weights", weightVanillaExtremeHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaExtremeHillsM = config.getInt("weightVanillaExtremeHillsM", "Weights", weightVanillaExtremeHillsM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaExtremeHillsPlus = config.getInt("weightVanillaExtremeHillsPlus", "Weights", weightVanillaExtremeHillsPlus, biomeWeightMin, biomeWeightMax, "");
            weightVanillaExtremeHillsPlusM = config.getInt("weightVanillaExtremeHillsPlusM", "Weights", weightVanillaExtremeHillsPlusM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaFlowerForest = config.getInt("weightVanillaFlowerForest", "Weights", weightVanillaFlowerForest, biomeWeightMin, biomeWeightMax, "");
            weightVanillaForest = config.getInt("weightVanillaForest", "Weights", weightVanillaForest, biomeWeightMin, biomeWeightMax, "");
            weightVanillaForestHills = config.getInt("weightVanillaForestHills", "Weights", weightVanillaForestHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaFrozenRiver = config.getInt("weightVanillaFrozenRiver", "Weights", weightVanillaFrozenRiver, biomeWeightMin, biomeWeightMax, "");
            weightVanillaIceMountains = config.getInt("weightVanillaIceMountains", "Weights", weightVanillaIceMountains, biomeWeightMin, biomeWeightMax, "");
            weightVanillaIcePlains = config.getInt("weightVanillaIcePlains", "Weights", weightVanillaIcePlains, biomeWeightMin, biomeWeightMax, "");
            weightVanillaIcePlainsSpikes = config.getInt("weightVanillaIcePlainsSpikes", "Weights", weightVanillaIcePlainsSpikes, biomeWeightMin, biomeWeightMax, "");
            weightVanillaJungle = config.getInt("weightVanillaJungle", "Weights", weightVanillaJungle, biomeWeightMin, biomeWeightMax, "");
            weightVanillaJungleEdge = config.getInt("weightVanillaJungleEdge", "Weights", weightVanillaJungleEdge, biomeWeightMin, biomeWeightMax, "");
            weightVanillaJungleEdgeM = config.getInt("weightVanillaJungleEdgeM", "Weights", weightVanillaJungleEdgeM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaJungleHills = config.getInt("weightVanillaJungleHills", "Weights", weightVanillaJungleHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaJungleM = config.getInt("weightVanillaJungleM", "Weights", weightVanillaJungleM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMegaSpruceTaiga = config.getInt("weightVanillaMegaSpruceTaiga", "Weights", weightVanillaMegaSpruceTaiga, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMegaTaiga = config.getInt("weightVanillaMegaTaiga", "Weights", weightVanillaMegaTaiga, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMegaTaigaHills = config.getInt("weightVanillaMegaTaigaHills", "Weights", weightVanillaMegaTaigaHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMesa = config.getInt("weightVanillaMesa", "Weights", weightVanillaMesa, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMesaBryce = config.getInt("weightVanillaMesaBryce", "Weights", weightVanillaMesaBryce, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMesaPlateau = config.getInt("weightVanillaMesaPlateau", "Weights", weightVanillaMesaPlateau, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMesaPlateau_F = config.getInt("weightVanillaMesaPlateau_F", "Weights", weightVanillaMesaPlateau_F, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMesaPlateauFM = config.getInt("weightVanillaMesaPlateauFM", "Weights", weightVanillaMesaPlateauFM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMesaPlateauM = config.getInt("weightVanillaMesaPlateauM", "Weights", weightVanillaMesaPlateauM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMushroomIsland = config.getInt("weightVanillaMushroomIsland", "Weights", weightVanillaMushroomIsland, biomeWeightMin, biomeWeightMax, "");
            weightVanillaMushroomIslandShore = config.getInt("weightVanillaMushroomIslandShore", "Weights", weightVanillaMushroomIslandShore, biomeWeightMin, biomeWeightMax, "");
            weightVanillaOcean = config.getInt("weightVanillaOcean", "Weights", weightVanillaOcean, biomeWeightMin, biomeWeightMax, "");
            weightVanillaPlains = config.getInt("weightVanillaPlains", "Weights", weightVanillaPlains, biomeWeightMin, biomeWeightMax, "");
            weightVanillaRiver = config.getInt("weightVanillaRiver", "Weights", weightVanillaRiver, biomeWeightMin, biomeWeightMax, "");
            weightVanillaRoofedForest = config.getInt("weightVanillaRoofedForest", "Weights", weightVanillaRoofedForest, biomeWeightMin, biomeWeightMax, "");
            weightVanillaRoofedForestM = config.getInt("weightVanillaRoofedForestM", "Weights", weightVanillaRoofedForestM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaSavanna = config.getInt("weightVanillaSavanna", "Weights", weightVanillaSavanna, biomeWeightMin, biomeWeightMax, "");
            weightVanillaSavannaM = config.getInt("weightVanillaSavannaM", "Weights", weightVanillaSavannaM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaSavannaPlateau = config.getInt("weightVanillaSavannaPlateau", "Weights", weightVanillaSavannaPlateau, biomeWeightMin, biomeWeightMax, "");
            weightVanillaSavannaPlateauM = config.getInt("weightVanillaSavannaPlateauM", "Weights", weightVanillaSavannaPlateauM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaStoneBeach = config.getInt("weightVanillaStoneBeach", "Weights", weightVanillaStoneBeach, biomeWeightMin, biomeWeightMax, "");
            weightVanillaSunflowerPlains = config.getInt("weightVanillaSunflowerPlains", "Weights", weightVanillaSunflowerPlains, biomeWeightMin, biomeWeightMax, "");
            weightVanillaSwampland = config.getInt("weightVanillaSwampland", "Weights", weightVanillaSwampland, biomeWeightMin, biomeWeightMax, "");
            weightVanillaSwamplandM = config.getInt("weightVanillaSwamplandM", "Weights", weightVanillaSwamplandM, biomeWeightMin, biomeWeightMax, "");
            weightVanillaTaiga = config.getInt("weightVanillaTaiga", "Weights", weightVanillaTaiga, biomeWeightMin, biomeWeightMax, "");
            weightVanillaTaigaHills = config.getInt("weightVanillaTaigaHills", "Weights", weightVanillaTaigaHills, biomeWeightMin, biomeWeightMax, "");
            weightVanillaTaigaM = config.getInt("weightVanillaTaigaM", "Weights", weightVanillaTaigaM, biomeWeightMin, biomeWeightMax, "");
            
            villageVanillaBeach = config.getBoolean("villageVanillaBeach", "Villages", villageVanillaBeach, "");
            villageVanillaBirchForest = config.getBoolean("villageVanillaBirchForest", "Villages", villageVanillaBirchForest, "");
            villageVanillaBirchForestHills = config.getBoolean("villageVanillaBirchForestHills", "Villages", villageVanillaBirchForestHills, "");
            villageVanillaBirchForestHillsM = config.getBoolean("villageVanillaBirchForestHillsM", "Villages", villageVanillaBirchForestHillsM, "");
            villageVanillaBirchForestM = config.getBoolean("villageVanillaBirchForestM", "Villages", villageVanillaBirchForestM, "");
            villageVanillaColdBeach = config.getBoolean("villageVanillaColdBeach", "Villages", villageVanillaColdBeach, "");
            villageVanillaColdTaiga = config.getBoolean("villageVanillaColdTaiga", "Villages", villageVanillaColdTaiga, "");
            villageVanillaColdTaigaHills = config.getBoolean("villageVanillaColdTaigaHills", "Villages", villageVanillaColdTaigaHills, "");
            villageVanillaColdTaigaM = config.getBoolean("villageVanillaColdTaigaM", "Villages", villageVanillaColdTaigaM, "");
            villageVanillaDeepOcean = config.getBoolean("villageVanillaDeepOcean", "Villages", villageVanillaDeepOcean, "");
            villageVanillaDesert = config.getBoolean("villageVanillaDesert", "Villages", villageVanillaDesert, "");
            villageVanillaDesertHills = config.getBoolean("villageVanillaDesertHills", "Villages", villageVanillaDesertHills, "");
            villageVanillaDesertM = config.getBoolean("villageVanillaDesertM", "Villages", villageVanillaDesertM, "");
            villageVanillaExtremeHills = config.getBoolean("villageVanillaExtremeHills", "Villages", villageVanillaExtremeHills, "");
            villageVanillaExtremeHillsM = config.getBoolean("villageVanillaExtremeHillsM", "Villages", villageVanillaExtremeHillsM, "");
            villageVanillaExtremeHillsPlus = config.getBoolean("villageVanillaExtremeHillsPlus", "Villages", villageVanillaExtremeHillsPlus, "");
            villageVanillaExtremeHillsPlusM = config.getBoolean("villageVanillaExtremeHillsPlusM", "Villages", villageVanillaExtremeHillsPlusM, "");
            villageVanillaFlowerForest = config.getBoolean("villageVanillaFlowerForest", "Villages", villageVanillaFlowerForest, "");
            villageVanillaForest = config.getBoolean("villageVanillaForest", "Villages", villageVanillaForest, "");
            villageVanillaForestHills = config.getBoolean("villageVanillaForestHills", "Villages", villageVanillaForestHills, "");
            //villageVanillaFrozenRiver = config.getBoolean("villageVanillaFrozenRiver", "Villages", villageVanillaFrozenRiver, "This setting is ignored. Frozen Rivers will always generate, even if set to false.");
            villageVanillaIceMountains = config.getBoolean("villageVanillaIceMountains", "Villages", villageVanillaIceMountains, "");
            villageVanillaIcePlains = config.getBoolean("villageVanillaIcePlains", "Villages", villageVanillaIcePlains, "");
            villageVanillaIcePlainsSpikes = config.getBoolean("villageVanillaIcePlainsSpikes", "Villages", villageVanillaIcePlainsSpikes, "");
            villageVanillaJungle = config.getBoolean("villageVanillaJungle", "Villages", villageVanillaJungle, "");
            villageVanillaJungleEdge = config.getBoolean("villageVanillaJungleEdge", "Villages", villageVanillaJungleEdge, "");
            villageVanillaJungleEdgeM = config.getBoolean("villageVanillaJungleEdgeM", "Villages", villageVanillaJungleEdgeM, "");
            villageVanillaJungleHills = config.getBoolean("villageVanillaJungleHills", "Villages", villageVanillaJungleHills, "");
            villageVanillaJungleM = config.getBoolean("villageVanillaJungleM", "Villages", villageVanillaJungleM, "");
            villageVanillaMegaSpruceTaiga = config.getBoolean("villageVanillaMegaSpruceTaiga", "Villages", villageVanillaMegaSpruceTaiga, "");
            villageVanillaMegaTaiga = config.getBoolean("villageVanillaMegaTaiga", "Villages", villageVanillaMegaTaiga, "");
            villageVanillaMegaTaigaHills = config.getBoolean("villageVanillaMegaTaigaHills", "Villages", villageVanillaMegaTaigaHills, "");
            villageVanillaMesa = config.getBoolean("villageVanillaMesa", "Villages", villageVanillaMesa, "");
            villageVanillaMesaBryce = config.getBoolean("villageVanillaMesaBryce", "Villages", villageVanillaMesaBryce, "");
            villageVanillaMesaPlateau = config.getBoolean("villageVanillaMesaPlateau", "Villages", villageVanillaMesaPlateau, "");
            villageVanillaMesaPlateau_F = config.getBoolean("villageVanillaMesaPlateau_F", "Villages", villageVanillaMesaPlateau_F, "");
            villageVanillaMesaPlateauFM = config.getBoolean("villageVanillaMesaPlateauFM", "Villages", villageVanillaMesaPlateauFM, "");
            villageVanillaMesaPlateauM = config.getBoolean("villageVanillaMesaPlateauM", "Villages", villageVanillaMesaPlateauM, "");
            villageVanillaMushroomIsland = config.getBoolean("villageVanillaMushroomIsland", "Villages", villageVanillaMushroomIsland, "");
            villageVanillaMushroomIslandShore = config.getBoolean("villageVanillaMushroomIslandShore", "Villages", villageVanillaMushroomIslandShore, "");
            villageVanillaOcean = config.getBoolean("villageVanillaOcean", "Villages", villageVanillaOcean, "");
            villageVanillaPlains = config.getBoolean("villageVanillaPlains", "Villages", villageVanillaPlains, "");
            //villageVanillaRiver = config.getBoolean("villageVanillaRiver", "Villages", villageVanillaRiver, "This setting is ignored. Rivers will always generate, even if set to false.");
            villageVanillaRoofedForest = config.getBoolean("villageVanillaRoofedForest", "Villages", villageVanillaRoofedForest, "");
            villageVanillaRoofedForestM = config.getBoolean("villageVanillaRoofedForestM", "Villages", villageVanillaRoofedForestM, "");
            villageVanillaSavanna = config.getBoolean("villageVanillaSavanna", "Villages", villageVanillaSavanna, "");
            villageVanillaSavannaM = config.getBoolean("villageVanillaSavannaM", "Villages", villageVanillaSavannaM, "");
            villageVanillaSavannaPlateau = config.getBoolean("villageVanillaSavannaPlateau", "Villages", villageVanillaSavannaPlateau, "");
            villageVanillaSavannaPlateauM = config.getBoolean("villageVanillaSavannaPlateauM", "Villages", villageVanillaSavannaPlateauM, "");
            villageVanillaStoneBeach = config.getBoolean("villageVanillaStoneBeach", "Villages", villageVanillaStoneBeach, "");
            villageVanillaSunflowerPlains = config.getBoolean("villageVanillaSunflowerPlains", "Villages", villageVanillaSunflowerPlains, "");
            villageVanillaSwampland = config.getBoolean("villageVanillaSwampland", "Villages", villageVanillaSwampland, "");
            villageVanillaSwamplandM = config.getBoolean("villageVanillaSwamplandM", "Villages", villageVanillaSwamplandM, "");
            villageVanillaTaiga = config.getBoolean("villageVanillaTaiga", "Villages", villageVanillaTaiga, "");
            villageVanillaTaigaHills = config.getBoolean("villageVanillaTaigaHills", "Villages", villageVanillaTaigaHills, "");
            villageVanillaTaigaM = config.getBoolean("villageVanillaTaigaM", "Villages", villageVanillaTaigaM, "");
		}
		catch (Exception e) 
		{
			FMLLog.log(Level.ERROR, e, "RTG has had a problem loading Vanilla configuration.");	
		}
		finally 
		{
			if (config.hasChanged())
			{
				config.save();
			}
		}
	}
}
