package rtg.config;

import java.io.File;

import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.config.Configuration;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

import org.apache.logging.log4j.Level;

public class ConfigEB 
{
	public static Configuration config;
	
	public static final int biomeWeightMin = 0;
	public static final int biomeWeightMax = 100;
	public static final int biomeWeightDefault = 10;
	
	public static boolean generateEBBiomes = true;
			
	public static boolean generateEBAlpineMountains = true;
	public static boolean generateEBAlpineMountainsEdge = true;
	public static boolean generateEBAlpineMountainsM = true;
	public static boolean generateEBAlpineTundra = true;
	public static boolean generateEBAspenForest = true;
	public static boolean generateEBAspenHills = true;
	public static boolean generateEBBadlands = true;
	public static boolean generateEBBasin = false;
	public static boolean generateEBBlossomHills = true;
	public static boolean generateEBBlossomWoods = true;
	public static boolean generateEBBorealArchipelago = true;
	public static boolean generateEBBorealForest = true;
	public static boolean generateEBBorealPlateau = true;
	public static boolean generateEBBorealPlateauM = true;
	public static boolean generateEBCarr = true;
	public static boolean generateEBClayHills = false;
	public static boolean generateEBClearing = true;
	public static boolean generateEBColdBorealForest = true;
	public static boolean generateEBColdCypressForest = true;
	public static boolean generateEBColdFirForest = true;
	public static boolean generateEBColdPineForest = true;
	public static boolean generateEBCreekBed = false;
	public static boolean generateEBCypressForest = true;
	public static boolean generateEBDesertArchipelago = true;
	public static boolean generateEBEphemeralLake = false;
	public static boolean generateEBEphemeralLakeEdge = false;
	public static boolean generateEBFens = true;
	public static boolean generateEBFirForest = true;
	public static boolean generateEBFloweryArchipelago = true;
	public static boolean generateEBForestedArchipelago = true;
	public static boolean generateEBForestedMountains = true;
	public static boolean generateEBForestedValley = true;
	public static boolean generateEBFrozenArchipelago = true;
	public static boolean generateEBGlacier = true;
	public static boolean generateEBGrassyArchipelago = true;
	public static boolean generateEBIceSheet = false;
	public static boolean generateEBKakadu = true;
	public static boolean generateEBLake = true;
	public static boolean generateEBLowHills = true;
	public static boolean generateEBMangroves = true;
	public static boolean generateEBMarsh = true;
	public static boolean generateEBMeadow = true;
	public static boolean generateEBMeadowM = true;
	public static boolean generateEBMountainousArchipelago = true;
	public static boolean generateEBMountains = true;
	public static boolean generateEBMountainsEdge = true;
	public static boolean generateEBOakForest = true;
	public static boolean generateEBOasis = true;
	public static boolean generateEBPineForest = true;
	public static boolean generateEBPineForestArchipelago = true;
	public static boolean generateEBPlateau = true;
	public static boolean generateEBPolarDesert = false;
	public static boolean generateEBPrairie = true;
	public static boolean generateEBRainforest = true;
	public static boolean generateEBRainforestValley = true;
	public static boolean generateEBRedDesert = true;
	public static boolean generateEBRiparianZone = true;
	public static boolean generateEBRockyDesert = false;
	public static boolean generateEBRockyHills = false;
	public static boolean generateEBRoofedShrublands = true;
	public static boolean generateEBSahara = true;
	public static boolean generateEBSandstoneCanyon = false;
	public static boolean generateEBSandstoneCanyons = false;
	public static boolean generateEBSandstoneRanges = false;
	public static boolean generateEBSandstoneRangesM = false;
	public static boolean generateEBScree = false;
	public static boolean generateEBScrub = false;
	public static boolean generateEBShield = true;
	public static boolean generateEBShrublands = true;
	public static boolean generateEBSilverPineForest = true;
	public static boolean generateEBSilverPineHills = true;
	public static boolean generateEBSnowyDesert = true;
	public static boolean generateEBSnowyPlateau = true;
	public static boolean generateEBSnowyRanges = true;
	public static boolean generateEBSnowyWastelands = false;
	public static boolean generateEBSteppe = true;
	public static boolean generateEBStoneCanyon = false;
	public static boolean generateEBStoneCanyons = false;
	public static boolean generateEBTropicalArchipelago = true;
	public static boolean generateEBTundra = true;
	public static boolean generateEBVolcano = false;
	public static boolean generateEBVolcanoM = false;
	public static boolean generateEBWastelands = false;
	public static boolean generateEBWoodlandField = true;
	public static boolean generateEBWoodlandHills = true;
	public static boolean generateEBWoodlandLake = true;
	public static boolean generateEBWoodlandLakeEdge = true;
	public static boolean generateEBWoodlands = true;
	public static boolean generateEBXericSavannah = true;
	public static boolean generateEBXericShrubland = true;
	
	public static int weightEBAlpineMountains = biomeWeightDefault;
	public static int weightEBAlpineMountainsEdge = biomeWeightDefault;
	public static int weightEBAlpineMountainsM = biomeWeightDefault;
	public static int weightEBAlpineTundra = biomeWeightDefault;
	public static int weightEBAspenForest = biomeWeightDefault;
	public static int weightEBAspenHills = biomeWeightDefault;
	public static int weightEBBadlands = biomeWeightDefault;
	public static int weightEBBasin = biomeWeightDefault;
	public static int weightEBBlossomHills = biomeWeightDefault;
	public static int weightEBBlossomWoods = biomeWeightDefault;
	public static int weightEBBorealArchipelago = biomeWeightDefault;
	public static int weightEBBorealForest = biomeWeightDefault;
	public static int weightEBBorealPlateau = biomeWeightDefault;
	public static int weightEBBorealPlateauM = biomeWeightDefault;
	public static int weightEBCarr = biomeWeightDefault;
	public static int weightEBClayHills = biomeWeightDefault;
	public static int weightEBClearing = biomeWeightDefault;
	public static int weightEBColdBorealForest = biomeWeightDefault;
	public static int weightEBColdCypressForest = biomeWeightDefault;
	public static int weightEBColdFirForest = biomeWeightDefault;
	public static int weightEBColdPineForest = biomeWeightDefault;
	public static int weightEBCreekBed = biomeWeightDefault;
	public static int weightEBCypressForest = biomeWeightDefault;
	public static int weightEBDesertArchipelago = biomeWeightDefault;
	public static int weightEBEphemeralLake = biomeWeightDefault;
	public static int weightEBEphemeralLakeEdge = biomeWeightDefault;
	public static int weightEBFens = biomeWeightDefault;
	public static int weightEBFirForest = biomeWeightDefault;
	public static int weightEBFloweryArchipelago = biomeWeightDefault;
	public static int weightEBForestedArchipelago = biomeWeightDefault;
	public static int weightEBForestedMountains = biomeWeightDefault;
	public static int weightEBForestedValley = biomeWeightDefault;
	public static int weightEBFrozenArchipelago = biomeWeightDefault;
	public static int weightEBGlacier = biomeWeightDefault;
	public static int weightEBGrassyArchipelago = biomeWeightDefault;
	public static int weightEBIceSheet = biomeWeightDefault;
	public static int weightEBKakadu = biomeWeightDefault;
	public static int weightEBLake = biomeWeightDefault;
	public static int weightEBLowHills = biomeWeightDefault;
	public static int weightEBMangroves = biomeWeightDefault;
	public static int weightEBMarsh = biomeWeightDefault;
	public static int weightEBMeadow = biomeWeightDefault;
	public static int weightEBMeadowM = biomeWeightDefault;
	public static int weightEBMountainousArchipelago = biomeWeightDefault;
	public static int weightEBMountains = biomeWeightDefault;
	public static int weightEBMountainsEdge = biomeWeightDefault;
	public static int weightEBOakForest = biomeWeightDefault;
	public static int weightEBOasis = biomeWeightDefault;
	public static int weightEBPineForest = biomeWeightDefault;
	public static int weightEBPineForestArchipelago = biomeWeightDefault;
	public static int weightEBPlateau = biomeWeightDefault;
	public static int weightEBPolarDesert = biomeWeightDefault;
	public static int weightEBPrairie = biomeWeightDefault;
	public static int weightEBRainforest = biomeWeightDefault;
	public static int weightEBRainforestValley = biomeWeightDefault;
	public static int weightEBRedDesert = biomeWeightDefault;
	public static int weightEBRiparianZone = biomeWeightDefault;
	public static int weightEBRockyDesert = biomeWeightDefault;
	public static int weightEBRockyHills = biomeWeightDefault;
	public static int weightEBRoofedShrublands = biomeWeightDefault;
	public static int weightEBSahara = biomeWeightDefault;
	public static int weightEBSandstoneCanyon = biomeWeightDefault;
	public static int weightEBSandstoneCanyons = biomeWeightDefault;
	public static int weightEBSandstoneRanges = biomeWeightDefault;
	public static int weightEBSandstoneRangesM = biomeWeightDefault;
	public static int weightEBScree = biomeWeightDefault;
	public static int weightEBScrub = biomeWeightDefault;
	public static int weightEBShield = biomeWeightDefault;
	public static int weightEBShrublands = biomeWeightDefault;
	public static int weightEBSilverPineForest = biomeWeightDefault;
	public static int weightEBSilverPineHills = biomeWeightDefault;
	public static int weightEBSnowyDesert = biomeWeightDefault;
	public static int weightEBSnowyPlateau = biomeWeightDefault;
	public static int weightEBSnowyRanges = biomeWeightDefault;
	public static int weightEBSnowyWastelands = biomeWeightDefault;
	public static int weightEBSteppe = biomeWeightDefault;
	public static int weightEBStoneCanyon = biomeWeightDefault;
	public static int weightEBStoneCanyons = biomeWeightDefault;
	public static int weightEBTropicalArchipelago = biomeWeightDefault;
	public static int weightEBTundra = biomeWeightDefault;
	public static int weightEBVolcano = biomeWeightDefault;
	public static int weightEBVolcanoM = biomeWeightDefault;
	public static int weightEBWastelands = biomeWeightDefault;
	public static int weightEBWoodlandField = biomeWeightDefault;
	public static int weightEBWoodlandHills = biomeWeightDefault;
	public static int weightEBWoodlandLake = biomeWeightDefault;
	public static int weightEBWoodlandLakeEdge = biomeWeightDefault;
	public static int weightEBWoodlands = biomeWeightDefault;
	public static int weightEBXericSavannah = biomeWeightDefault;
	public static int weightEBXericShrubland = biomeWeightDefault;
		
	public static void init(File configFile) 
	{
		config = new Configuration(configFile);
	
		try 
		{
			config.load();
			
			generateEBBiomes = config.getBoolean("Generate EB Biomes", "EB Biomes", true, "");
			
			generateEBAlpineMountains = config.getBoolean("generateEBAlpineMountains", "EB Biomes", generateEBAlpineMountains, "");
			generateEBAlpineMountainsEdge = config.getBoolean("generateEBAlpineMountainsEdge", "EB Biomes", generateEBAlpineMountainsEdge, "");
			generateEBAlpineMountainsM = config.getBoolean("generateEBAlpineMountainsM", "EB Biomes", generateEBAlpineMountainsM, "");
			generateEBAlpineTundra = config.getBoolean("generateEBAlpineTundra", "EB Biomes", generateEBAlpineTundra, "");
			generateEBAspenForest = config.getBoolean("generateEBAspenForest", "EB Biomes", generateEBAspenForest, "");
			generateEBAspenHills = config.getBoolean("generateEBAspenHills", "EB Biomes", generateEBAspenHills, "");
			generateEBBadlands = config.getBoolean("generateEBBadlands", "EB Biomes", generateEBBadlands, "");
			generateEBBasin = config.getBoolean("generateEBBasin", "EB Biomes", generateEBBasin, "");
			generateEBBlossomHills = config.getBoolean("generateEBBlossomHills", "EB Biomes", generateEBBlossomHills, "");
			generateEBBlossomWoods = config.getBoolean("generateEBBlossomWoods", "EB Biomes", generateEBBlossomWoods, "");
			generateEBBorealArchipelago = config.getBoolean("generateEBBorealArchipelago", "EB Biomes", generateEBBorealArchipelago, "");
			generateEBBorealForest = config.getBoolean("generateEBBorealForest", "EB Biomes", generateEBBorealForest, "");
			generateEBBorealPlateau = config.getBoolean("generateEBBorealPlateau", "EB Biomes", generateEBBorealPlateau, "");
			generateEBBorealPlateauM = config.getBoolean("generateEBBorealPlateauM", "EB Biomes", generateEBBorealPlateauM, "");
			generateEBCarr = config.getBoolean("generateEBCarr", "EB Biomes", generateEBCarr, "");
			generateEBClayHills = config.getBoolean("generateEBClayHills", "EB Biomes", generateEBClayHills, "");
			generateEBClearing = config.getBoolean("generateEBClearing", "EB Biomes", generateEBClearing, "");
			generateEBColdBorealForest = config.getBoolean("generateEBColdBorealForest", "EB Biomes", generateEBColdBorealForest, "");
			generateEBColdCypressForest = config.getBoolean("generateEBColdCypressForest", "EB Biomes", generateEBColdCypressForest, "");
			generateEBColdFirForest = config.getBoolean("generateEBColdFirForest", "EB Biomes", generateEBColdFirForest, "");
			generateEBColdPineForest = config.getBoolean("generateEBColdPineForest", "EB Biomes", generateEBColdPineForest, "");
			generateEBCreekBed = config.getBoolean("generateEBCreekBed", "EB Biomes", generateEBCreekBed, "");
			generateEBCypressForest = config.getBoolean("generateEBCypressForest", "EB Biomes", generateEBCypressForest, "");
			generateEBDesertArchipelago = config.getBoolean("generateEBDesertArchipelago", "EB Biomes", generateEBDesertArchipelago, "");
			generateEBEphemeralLake = config.getBoolean("generateEBEphemeralLake", "EB Biomes", generateEBEphemeralLake, "");
			generateEBEphemeralLakeEdge = config.getBoolean("generateEBEphemeralLakeEdge", "EB Biomes", generateEBEphemeralLakeEdge, "");
			generateEBFens = config.getBoolean("generateEBFens", "EB Biomes", generateEBFens, "");
			generateEBFirForest = config.getBoolean("generateEBFirForest", "EB Biomes", generateEBFirForest, "");
			generateEBFloweryArchipelago = config.getBoolean("generateEBFloweryArchipelago", "EB Biomes", generateEBFloweryArchipelago, "");
			generateEBForestedArchipelago = config.getBoolean("generateEBForestedArchipelago", "EB Biomes", generateEBForestedArchipelago, "");
			generateEBForestedMountains = config.getBoolean("generateEBForestedMountains", "EB Biomes", generateEBForestedMountains, "");
			generateEBForestedValley = config.getBoolean("generateEBForestedValley", "EB Biomes", generateEBForestedValley, "");
			generateEBFrozenArchipelago = config.getBoolean("generateEBFrozenArchipelago", "EB Biomes", generateEBFrozenArchipelago, "");
			generateEBGlacier = config.getBoolean("generateEBGlacier", "EB Biomes", generateEBGlacier, "");
			generateEBGrassyArchipelago = config.getBoolean("generateEBGrassyArchipelago", "EB Biomes", generateEBGrassyArchipelago, "");
			generateEBIceSheet = config.getBoolean("generateEBIceSheet", "EB Biomes", generateEBIceSheet, "");
			generateEBKakadu = config.getBoolean("generateEBKakadu", "EB Biomes", generateEBKakadu, "");
			generateEBLake = config.getBoolean("generateEBLake", "EB Biomes", generateEBLake, "");
			generateEBLowHills = config.getBoolean("generateEBLowHills", "EB Biomes", generateEBLowHills, "");
			generateEBMangroves = config.getBoolean("generateEBMangroves", "EB Biomes", generateEBMangroves, "");
			generateEBMarsh = config.getBoolean("generateEBMarsh", "EB Biomes", generateEBMarsh, "");
			generateEBMeadow = config.getBoolean("generateEBMeadow", "EB Biomes", generateEBMeadow, "");
			generateEBMeadowM = config.getBoolean("generateEBMeadowM", "EB Biomes", generateEBMeadowM, "");
			generateEBMountainousArchipelago = config.getBoolean("generateEBMountainousArchipelago", "EB Biomes", generateEBMountainousArchipelago, "");
			generateEBMountains = config.getBoolean("generateEBMountains", "EB Biomes", generateEBMountains, "");
			generateEBMountainsEdge = config.getBoolean("generateEBMountainsEdge", "EB Biomes", generateEBMountainsEdge, "");
			generateEBOakForest = config.getBoolean("generateEBOakForest", "EB Biomes", generateEBOakForest, "");
			generateEBOasis = config.getBoolean("generateEBOasis", "EB Biomes", generateEBOasis, "");
			generateEBPineForest = config.getBoolean("generateEBPineForest", "EB Biomes", generateEBPineForest, "");
			generateEBPineForestArchipelago = config.getBoolean("generateEBPineForestArchipelago", "EB Biomes", generateEBPineForestArchipelago, "");
			generateEBPlateau = config.getBoolean("generateEBPlateau", "EB Biomes", generateEBPlateau, "");
			generateEBPolarDesert = config.getBoolean("generateEBPolarDesert", "EB Biomes", generateEBPolarDesert, "");
			generateEBPrairie = config.getBoolean("generateEBPrairie", "EB Biomes", generateEBPrairie, "");
			generateEBRainforest = config.getBoolean("generateEBRainforest", "EB Biomes", generateEBRainforest, "");
			generateEBRainforestValley = config.getBoolean("generateEBRainforestValley", "EB Biomes", generateEBRainforestValley, "");
			generateEBRedDesert = config.getBoolean("generateEBRedDesert", "EB Biomes", generateEBRedDesert, "");
			generateEBRiparianZone = config.getBoolean("generateEBRiparianZone", "EB Biomes", generateEBRiparianZone, "");
			generateEBRockyDesert = config.getBoolean("generateEBRockyDesert", "EB Biomes", generateEBRockyDesert, "");
			generateEBRockyHills = config.getBoolean("generateEBRockyHills", "EB Biomes", generateEBRockyHills, "");
			generateEBRoofedShrublands = config.getBoolean("generateEBRoofedShrublands", "EB Biomes", generateEBRoofedShrublands, "");
			generateEBSahara = config.getBoolean("generateEBSahara", "EB Biomes", generateEBSahara, "");
			generateEBSandstoneCanyon = config.getBoolean("generateEBSandstoneCanyon", "EB Biomes", generateEBSandstoneCanyon, "");
			generateEBSandstoneCanyons = config.getBoolean("generateEBSandstoneCanyons", "EB Biomes", generateEBSandstoneCanyons, "");
			generateEBSandstoneRanges = config.getBoolean("generateEBSandstoneRanges", "EB Biomes", generateEBSandstoneRanges, "");
			generateEBSandstoneRangesM = config.getBoolean("generateEBSandstoneRangesM", "EB Biomes", generateEBSandstoneRangesM, "");
			generateEBScree = config.getBoolean("generateEBScree", "EB Biomes", generateEBScree, "");
			generateEBScrub = config.getBoolean("generateEBScrub", "EB Biomes", generateEBScrub, "");
			generateEBShield = config.getBoolean("generateEBShield", "EB Biomes", generateEBShield, "");
			generateEBShrublands = config.getBoolean("generateEBShrublands", "EB Biomes", generateEBShrublands, "");
			generateEBSilverPineForest = config.getBoolean("generateEBSilverPineForest", "EB Biomes", generateEBSilverPineForest, "");
			generateEBSilverPineHills = config.getBoolean("generateEBSilverPineHills", "EB Biomes", generateEBSilverPineHills, "");
			generateEBSnowyDesert = config.getBoolean("generateEBSnowyDesert", "EB Biomes", generateEBSnowyDesert, "");
			generateEBSnowyPlateau = config.getBoolean("generateEBSnowyPlateau", "EB Biomes", generateEBSnowyPlateau, "");
			generateEBSnowyRanges = config.getBoolean("generateEBSnowyRanges", "EB Biomes", generateEBSnowyRanges, "");
			generateEBSnowyWastelands = config.getBoolean("generateEBSnowyWastelands", "EB Biomes", generateEBSnowyWastelands, "");
			generateEBSteppe = config.getBoolean("generateEBSteppe", "EB Biomes", generateEBSteppe, "");
			generateEBStoneCanyon = config.getBoolean("generateEBStoneCanyon", "EB Biomes", generateEBStoneCanyon, "");
			generateEBStoneCanyons = config.getBoolean("generateEBStoneCanyons", "EB Biomes", generateEBStoneCanyons, "");
			generateEBTropicalArchipelago = config.getBoolean("generateEBTropicalArchipelago", "EB Biomes", generateEBTropicalArchipelago, "");
			generateEBTundra = config.getBoolean("generateEBTundra", "EB Biomes", generateEBTundra, "");
			generateEBVolcano = config.getBoolean("generateEBVolcano", "EB Biomes", generateEBVolcano, "");
			generateEBVolcanoM = config.getBoolean("generateEBVolcanoM", "EB Biomes", generateEBVolcanoM, "");
			generateEBWastelands = config.getBoolean("generateEBWastelands", "EB Biomes", generateEBWastelands, "");
			generateEBWoodlandField = config.getBoolean("generateEBWoodlandField", "EB Biomes", generateEBWoodlandField, "");
			generateEBWoodlandHills = config.getBoolean("generateEBWoodlandHills", "EB Biomes", generateEBWoodlandHills, "");
			generateEBWoodlandLake = config.getBoolean("generateEBWoodlandLake", "EB Biomes", generateEBWoodlandLake, "");
			generateEBWoodlandLakeEdge = config.getBoolean("generateEBWoodlandLakeEdge", "EB Biomes", generateEBWoodlandLakeEdge, "");
			generateEBWoodlands = config.getBoolean("generateEBWoodlands", "EB Biomes", generateEBWoodlands, "");
			generateEBXericSavannah = config.getBoolean("generateEBXericSavannah", "EB Biomes", generateEBXericSavannah, "");
			generateEBXericShrubland = config.getBoolean("generateEBXericShrubland", "EB Biomes", generateEBXericShrubland, "");
			
			weightEBAlpineMountains = config.getInt("weightEBAlpineMountains", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBAlpineMountainsEdge = config.getInt("weightEBAlpineMountainsEdge", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBAlpineMountainsM = config.getInt("weightEBAlpineMountainsM", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBAlpineTundra = config.getInt("weightEBAlpineTundra", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBAspenForest = config.getInt("weightEBAspenForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBAspenHills = config.getInt("weightEBAspenHills", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBadlands = config.getInt("weightEBBadlands", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBasin = config.getInt("weightEBBasin", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBlossomHills = config.getInt("weightEBBlossomHills", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBlossomWoods = config.getInt("weightEBBlossomWoods", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBorealArchipelago = config.getInt("weightEBBorealArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBorealForest = config.getInt("weightEBBorealForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBorealPlateau = config.getInt("weightEBBorealPlateau", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBBorealPlateauM = config.getInt("weightEBBorealPlateauM", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBCarr = config.getInt("weightEBCarr", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBClayHills = config.getInt("weightEBClayHills", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBClearing = config.getInt("weightEBClearing", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBColdBorealForest = config.getInt("weightEBColdBorealForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBColdCypressForest = config.getInt("weightEBColdCypressForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBColdFirForest = config.getInt("weightEBColdFirForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBColdPineForest = config.getInt("weightEBColdPineForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBCreekBed = config.getInt("weightEBCreekBed", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBCypressForest = config.getInt("weightEBCypressForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBDesertArchipelago = config.getInt("weightEBDesertArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBEphemeralLake = config.getInt("weightEBEphemeralLake", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBEphemeralLakeEdge = config.getInt("weightEBEphemeralLakeEdge", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBFens = config.getInt("weightEBFens", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBFirForest = config.getInt("weightEBFirForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBFloweryArchipelago = config.getInt("weightEBFloweryArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBForestedArchipelago = config.getInt("weightEBForestedArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBForestedMountains = config.getInt("weightEBForestedMountains", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBForestedValley = config.getInt("weightEBForestedValley", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBFrozenArchipelago = config.getInt("weightEBFrozenArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBGlacier = config.getInt("weightEBGlacier", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBGrassyArchipelago = config.getInt("weightEBGrassyArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBIceSheet = config.getInt("weightEBIceSheet", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBKakadu = config.getInt("weightEBKakadu", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBLake = config.getInt("weightEBLake", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBLowHills = config.getInt("weightEBLowHills", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBMangroves = config.getInt("weightEBMangroves", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBMarsh = config.getInt("weightEBMarsh", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBMeadow = config.getInt("weightEBMeadow", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBMeadowM = config.getInt("weightEBMeadowM", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBMountainousArchipelago = config.getInt("weightEBMountainousArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBMountains = config.getInt("weightEBMountains", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBMountainsEdge = config.getInt("weightEBMountainsEdge", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBOakForest = config.getInt("weightEBOakForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBOasis = config.getInt("weightEBOasis", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBPineForest = config.getInt("weightEBPineForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBPineForestArchipelago = config.getInt("weightEBPineForestArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBPlateau = config.getInt("weightEBPlateau", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBPolarDesert = config.getInt("weightEBPolarDesert", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBPrairie = config.getInt("weightEBPrairie", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBRainforest = config.getInt("weightEBRainforest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBRainforestValley = config.getInt("weightEBRainforestValley", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBRedDesert = config.getInt("weightEBRedDesert", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBRiparianZone = config.getInt("weightEBRiparianZone", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBRockyDesert = config.getInt("weightEBRockyDesert", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBRockyHills = config.getInt("weightEBRockyHills", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBRoofedShrublands = config.getInt("weightEBRoofedShrublands", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSahara = config.getInt("weightEBSahara", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSandstoneCanyon = config.getInt("weightEBSandstoneCanyon", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSandstoneCanyons = config.getInt("weightEBSandstoneCanyons", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSandstoneRanges = config.getInt("weightEBSandstoneRanges", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSandstoneRangesM = config.getInt("weightEBSandstoneRangesM", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBScree = config.getInt("weightEBScree", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBScrub = config.getInt("weightEBScrub", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBShield = config.getInt("weightEBShield", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBShrublands = config.getInt("weightEBShrublands", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSilverPineForest = config.getInt("weightEBSilverPineForest", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSilverPineHills = config.getInt("weightEBSilverPineHills", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSnowyDesert = config.getInt("weightEBSnowyDesert", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSnowyPlateau = config.getInt("weightEBSnowyPlateau", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSnowyRanges = config.getInt("weightEBSnowyRanges", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSnowyWastelands = config.getInt("weightEBSnowyWastelands", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBSteppe = config.getInt("weightEBSteppe", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBStoneCanyon = config.getInt("weightEBStoneCanyon", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBStoneCanyons = config.getInt("weightEBStoneCanyons", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBTropicalArchipelago = config.getInt("weightEBTropicalArchipelago", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBTundra = config.getInt("weightEBTundra", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBVolcano = config.getInt("weightEBVolcano", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBVolcanoM = config.getInt("weightEBVolcanoM", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBWastelands = config.getInt("weightEBWastelands", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBWoodlandField = config.getInt("weightEBWoodlandField", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBWoodlandHills = config.getInt("weightEBWoodlandHills", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBWoodlandLake = config.getInt("weightEBWoodlandLake", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBWoodlandLakeEdge = config.getInt("weightEBWoodlandLakeEdge", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBWoodlands = config.getInt("weightEBWoodlands", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBXericSavannah = config.getInt("weightEBXericSavannah", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
			weightEBXericShrubland = config.getInt("weightEBXericShrubland", "EB Biome Weights", biomeWeightDefault, biomeWeightMin, biomeWeightMax, "");
		}
		catch (Exception e)
		{
			FMLLog.log(Level.ERROR, e, "RTG has had a problem loading EB configuration.");	
		}
		finally 
		{
			if (config.hasChanged())
			{
				config.save();
			}
		}
	}
}
