package teamrtg.rtg.mods.vanilla;

import teamrtg.rtg.api.mods.ModBiomes;
import teamrtg.rtg.mods.vanilla.biomes.*;
import teamrtg.rtg.world.gen.ChunkProviderRTG;

/**
 * @author topisani
 */
public class RealisticVanillaBiomes extends ModBiomes {

    public RealisticBiomeVanillaBeach BEACH;
    public RealisticBiomeVanillaBirchForest BIRCH_FOREST;
    public RealisticBiomeVanillaBirchForestHills BIRCH_FOREST_HILLS;
    public RealisticBiomeVanillaBirchForestHillsM BIRCH_FOREST_HILLS_M;
    public RealisticBiomeVanillaBirchForestM BIRCH_FOREST_M;
    public RealisticBiomeVanillaColdBeach COLD_BEACH;
    public RealisticBiomeVanillaColdTaiga COLD_TAIGA;
    public RealisticBiomeVanillaColdTaigaHills COLD_TAIGA_HILLS;
    public RealisticBiomeVanillaColdTaigaM COLD_TAIGA_M;
    public RealisticBiomeVanillaDeepOcean DEEP_OCEAN;
    public RealisticBiomeVanillaDesert DESERT;
    public RealisticBiomeVanillaDesertHills DESERT_HILLS;
    public RealisticBiomeVanillaDesertM DESERT_M;
    public RealisticBiomeVanillaExtremeHills EXTREME_HILLS;
    public RealisticBiomeVanillaExtremeHillsEdge EXTREME_HILLS_EDGE;
    public RealisticBiomeVanillaExtremeHillsM EXTREME_HILLS_M;
    public RealisticBiomeVanillaExtremeHillsPlus EXTREME_HILLS_PLUS;
    public RealisticBiomeVanillaExtremeHillsPlusM EXTREME_HILLS_PLUS_M;
    public RealisticBiomeVanillaFlowerForest FLOWER_FOREST;
    public RealisticBiomeVanillaForest FOREST;
    public RealisticBiomeVanillaForestHills FOREST_HILLS;
    public RealisticBiomeVanillaFrozenOcean FROZEN_OCEAN;
    public RealisticBiomeVanillaFrozenRiver FROZEN_RIVER;
    public RealisticBiomeVanillaIceMountains ICE_MOUNTAINS;
    public RealisticBiomeVanillaIcePlains ICE_PLAINS;
    public RealisticBiomeVanillaIcePlainsSpikes ICE_PLAINS_SPIKES;
    public RealisticBiomeVanillaJungle JUNGLE;
    public RealisticBiomeVanillaJungleEdge JUNGLE_EDGE;
    public RealisticBiomeVanillaJungleEdgeM JUNGLE_EDGE_M;
    public RealisticBiomeVanillaJungleHills JUNGLE_HILLS;
    public RealisticBiomeVanillaJungleM JUNGLE_M;
    public RealisticBiomeVanillaMegaSpruceTaiga MEGA_SPRUCE_TAIGA;
    public RealisticBiomeVanillaMegaTaiga MEGA_TAIGA;
    public RealisticBiomeVanillaMegaTaigaHills MEGA_TAIGA_HILLS;
    public RealisticBiomeVanillaMesa MESA;
    public RealisticBiomeVanillaMesaBryce MESA_BRYCE;
    public RealisticBiomeVanillaMesaPlateau MESA_PLATEAU;
    public RealisticBiomeVanillaMesaPlateauF MESA_PLATEAU_F;
    public RealisticBiomeVanillaMesaPlateauFM MESA_PLATEAU_F_M;
    public RealisticBiomeVanillaMesaPlateauM MESA_PLATEAU_M;
    public RealisticBiomeVanillaMushroomIsland MUSHROOM_ISLAND;
    public RealisticBiomeVanillaMushroomIslandShore MUSHROOM_ISLAND_SHORE;
    public RealisticBiomeVanillaOcean OCEAN;
    public RealisticBiomeVanillaPlains PLAINS;
    public RealisticBiomeVanillaRedwoodTaigaHills REDWOOD_TAIGA_HILLS;
    public RealisticBiomeVanillaRiver RIVER;
    public RealisticBiomeVanillaRoofedForest ROOFED_FOREST;
    public RealisticBiomeVanillaRoofedForestM ROOFED_FOREST_M;
    public RealisticBiomeVanillaSavanna SAVANNA;
    public RealisticBiomeVanillaSavannaM SAVANNA_M;
    public RealisticBiomeVanillaSavannaPlateau SAVANNA_PLATEAU;
    public RealisticBiomeVanillaSavannaPlateauM SAVANNA_PLATEAU_M;
    public RealisticBiomeVanillaStoneBeach STONE_BEACH;
    public RealisticBiomeVanillaSunflowerPlains SUNFLOWER_PLAINS;
    public RealisticBiomeVanillaSwampland SWAMPLAND;
    public RealisticBiomeVanillaSwamplandM SWAMPLAND_M;
    public RealisticBiomeVanillaTaiga TAIGA;
    public RealisticBiomeVanillaTaigaHills TAIGA_HILLS;
    public RealisticBiomeVanillaTaigaM TAIGA_M;

    @Override
    public void initBiomes(ChunkProviderRTG chunkProvider) {
        addBiome(BEACH = new RealisticBiomeVanillaBeach(chunkProvider));
        addBiome(BIRCH_FOREST = new RealisticBiomeVanillaBirchForest(chunkProvider));
        addBiome(BIRCH_FOREST_HILLS = new RealisticBiomeVanillaBirchForestHills(chunkProvider));
        addBiome(BIRCH_FOREST_HILLS_M = new RealisticBiomeVanillaBirchForestHillsM(chunkProvider));
        addBiome(BIRCH_FOREST_M = new RealisticBiomeVanillaBirchForestM(chunkProvider));
        addBiome(COLD_BEACH = new RealisticBiomeVanillaColdBeach(chunkProvider));
        addBiome(COLD_TAIGA = new RealisticBiomeVanillaColdTaiga(chunkProvider));
        addBiome(COLD_TAIGA_HILLS = new RealisticBiomeVanillaColdTaigaHills(chunkProvider));
        addBiome(COLD_TAIGA_M = new RealisticBiomeVanillaColdTaigaM(chunkProvider));
        addBiome(DEEP_OCEAN = new RealisticBiomeVanillaDeepOcean(chunkProvider));
        addBiome(DESERT = new RealisticBiomeVanillaDesert(chunkProvider));
        addBiome(DESERT_HILLS = new RealisticBiomeVanillaDesertHills(chunkProvider));
        addBiome(DESERT_M = new RealisticBiomeVanillaDesertM(chunkProvider));
        addBiome(EXTREME_HILLS = new RealisticBiomeVanillaExtremeHills(chunkProvider));
        addBiome(EXTREME_HILLS_EDGE = new RealisticBiomeVanillaExtremeHillsEdge(chunkProvider));
        addBiome(EXTREME_HILLS_M = new RealisticBiomeVanillaExtremeHillsM(chunkProvider));
        addBiome(EXTREME_HILLS_PLUS = new RealisticBiomeVanillaExtremeHillsPlus(chunkProvider));
        addBiome(EXTREME_HILLS_PLUS_M = new RealisticBiomeVanillaExtremeHillsPlusM(chunkProvider));
        addBiome(FLOWER_FOREST = new RealisticBiomeVanillaFlowerForest(chunkProvider));
        addBiome(FOREST = new RealisticBiomeVanillaForest(chunkProvider));
        addBiome(FOREST_HILLS = new RealisticBiomeVanillaForestHills(chunkProvider));
        addBiome(FROZEN_OCEAN = new RealisticBiomeVanillaFrozenOcean(chunkProvider));
        addBiome(FROZEN_RIVER = new RealisticBiomeVanillaFrozenRiver(chunkProvider));
        addBiome(ICE_MOUNTAINS = new RealisticBiomeVanillaIceMountains(chunkProvider));
        addBiome(ICE_PLAINS = new RealisticBiomeVanillaIcePlains(chunkProvider));
        addBiome(ICE_PLAINS_SPIKES = new RealisticBiomeVanillaIcePlainsSpikes(chunkProvider));
        addBiome(JUNGLE = new RealisticBiomeVanillaJungle(chunkProvider));
        addBiome(JUNGLE_EDGE = new RealisticBiomeVanillaJungleEdge(chunkProvider));
        addBiome(JUNGLE_EDGE_M = new RealisticBiomeVanillaJungleEdgeM(chunkProvider));
        addBiome(JUNGLE_HILLS = new RealisticBiomeVanillaJungleHills(chunkProvider));
        addBiome(JUNGLE_M = new RealisticBiomeVanillaJungleM(chunkProvider));
        addBiome(MEGA_SPRUCE_TAIGA = new RealisticBiomeVanillaMegaSpruceTaiga(chunkProvider));
        addBiome(MEGA_TAIGA = new RealisticBiomeVanillaMegaTaiga(chunkProvider));
        addBiome(MEGA_TAIGA_HILLS = new RealisticBiomeVanillaMegaTaigaHills(chunkProvider));
        addBiome(MESA = new RealisticBiomeVanillaMesa(chunkProvider));
        addBiome(MESA_BRYCE = new RealisticBiomeVanillaMesaBryce(chunkProvider));
        addBiome(MESA_PLATEAU = new RealisticBiomeVanillaMesaPlateau(chunkProvider));
        addBiome(MESA_PLATEAU_F = new RealisticBiomeVanillaMesaPlateauF(chunkProvider));
        addBiome(MESA_PLATEAU_F_M = new RealisticBiomeVanillaMesaPlateauFM(chunkProvider));
        addBiome(MESA_PLATEAU_M = new RealisticBiomeVanillaMesaPlateauM(chunkProvider));
        addBiome(MUSHROOM_ISLAND = new RealisticBiomeVanillaMushroomIsland(chunkProvider));
        addBiome(MUSHROOM_ISLAND_SHORE = new RealisticBiomeVanillaMushroomIslandShore(chunkProvider));
        addBiome(OCEAN = new RealisticBiomeVanillaOcean(chunkProvider));
        addBiome(PLAINS = new RealisticBiomeVanillaPlains(chunkProvider));
        addBiome(REDWOOD_TAIGA_HILLS = new RealisticBiomeVanillaRedwoodTaigaHills(chunkProvider));
        addBiome(RIVER = new RealisticBiomeVanillaRiver(chunkProvider));
        addBiome(ROOFED_FOREST = new RealisticBiomeVanillaRoofedForest(chunkProvider));
        addBiome(ROOFED_FOREST_M = new RealisticBiomeVanillaRoofedForestM(chunkProvider));
        addBiome(SAVANNA = new RealisticBiomeVanillaSavanna(chunkProvider));
        addBiome(SAVANNA_M = new RealisticBiomeVanillaSavannaM(chunkProvider));
        addBiome(SAVANNA_PLATEAU = new RealisticBiomeVanillaSavannaPlateau(chunkProvider));
        addBiome(SAVANNA_PLATEAU_M = new RealisticBiomeVanillaSavannaPlateauM(chunkProvider));
        addBiome(STONE_BEACH = new RealisticBiomeVanillaStoneBeach(chunkProvider));
        addBiome(SUNFLOWER_PLAINS = new RealisticBiomeVanillaSunflowerPlains(chunkProvider));
        addBiome(SWAMPLAND = new RealisticBiomeVanillaSwampland(chunkProvider));
        addBiome(SWAMPLAND_M = new RealisticBiomeVanillaSwamplandM(chunkProvider));
        addBiome(TAIGA = new RealisticBiomeVanillaTaiga(chunkProvider));
        addBiome(TAIGA_HILLS = new RealisticBiomeVanillaTaigaHills(chunkProvider));
        addBiome(TAIGA_M = new RealisticBiomeVanillaTaigaM(chunkProvider));
    }
}
